apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pga
  namespace: monitoring
spec:
  encryptedData:
    password: AgBOTn1DY9XGX/AMPabcl43WDBAn8FCMd+mJSbDn7VlbkEvw63PWdPDY//rU2ufU9/X7Inc+HujCV4J6aviWEIiA15w27VcmObnu6C2HnSGLXEm0OXpGZm5zVooi0QCXhbpTY87DT+F7bVShBHDlKz+6xP2kJl53hSZP08gGGMC2XRWDFBrCEIFkzP/8+oTcTtInKYZ3ntrAwNuLfnjV8FQWBJAX0b7j4aNhOXBHtG644YmNaBe6FYsNEaQ59tsg3ywLUch5k7ju4+3HGqwem8jifvH+BNU7Ro528NpYy+Tb8lniEFbSgyD2temjteawCjOtnkfa+kzd3fEW/y+eX2ohz7DsYHwxFPn45p5Mw4U3pRm6yUSZjMtQzV0RoL2yYMw9H6F1ooIH7ItLAhpoM5kkremQ7ZEwjQB/Wu91HNGy0ACIf+H3qppTOteLkliEYZVLm9U9sfhZDoxBxMg2yysMPgnoAoUAAR+dKk6yfPDc2AMj4T+wU628hncOEGNxQM/MnspTI5A04/IlKptN8h9Vz9yqSrRgqCn/A1GXHjU7nefNFiH9OR1bvhqF46EkYhOwPtT09gfsaaBHYPMN6QTjdy8gfSQDRMS2R03itK808DWoFOZuKIeBGT7vy4Q7lqxuslmVu5cfsm5S1vb9KnRzVFe7Be0ljKeDSmwPXfeC02TAtSCPJNX5SXgl+C0ko7IIUR9hKDG49QCUbvB3A5x6
  template:
    metadata:
      creationTimestamp: null
      name: pga
      namespace: monitoring

