apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "migration-job.fullname" . }}
  label: "resepties-migration-tool"
spec:
  backoffLimit: 0
    template:
      spec:
        containers:
        - name: {{ "migration-tool-c" }}
          image: "{{ .Values.migration-tool.image.repository }}:{{ .Values.migration-tool.image.tag }}"
          env:
          - name: "ASPNETCORE_ENVIRONMENT"
            value: "Kubernetes"
          volumeMounts:
          - name: secretappsettings
            mountPath: /app/secrets
            readOnly: true
          - name: secretdb
            mountPath: /app/secrets
            readOnly: true
        volumes:
        - name: secretappsettings
          secret:
            secretName: {{ .Values.migration-tool.secretAppsettingsName }}
        - name: secretdb
          secret:
            secretName: {{ .Values.migration-tool.secretDbSettingsName }}
        restartPolicy: Never
        {{- with .Values.migration-tool.nodeSelector }}
        nodeSelector:
            {{- toYaml . | nindent 8 }}
        {{- end }}
