apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kc-general
  namespace: auth
spec:
  encryptedData:
    admin-pass: AgARPImQVE0rPeo3cHMU7eUw2bCXPjWIfPYAoaJ8fHQgeVpCbqeKuUlc2WG7YRNkLNGaPPaAZUpq3EWbIpiDtu6ctQZy5n//5eApdE3owgmjFwQML3bL2im53EWoiNUq4nXMbK4xLz31RNGLQxf6NT5sINYNeN95QRpn+AiENc7lvK1Ozcmy3AHs/MNo2m+uwdQLE8qTHmc7ZyEpXOEzfJmIlfD1Wf6BufQRIx38qPCGvXnsrPblY6VqSV2h4ojdGnMC7OOYLLuhtREqxSg8RgbYQnJX06BI3seueMNbL5GbqR4M1EeLPc6wzm9gl/4cZAeXMor6WLdVtjkV817j/1oWcxMBB+MbyMTFiWZJtaNrwkoAPUvEYKLmylPOVdxf5hVobfjKjNkODgJob2r9HYw9Sko/TvnADkAuCOMJi8HQUyw6FoglLFlw0Hm3bjqus3ynnCNTqq8Rmo/iB11rEn0eUsRvSSC0GRtdwO3xPTEaRjvTK//zlgb1pEIAmbnu/w02/D3ybx0+1XLDBj4MD/DPawShNbrKDUMD5b2k/pgrm7NDdUQa5zDnVhCWi6Qs9QEd1RY0haAzU4zIvey4SV1ZQtDCHN33rleXVTvvcB21WX344cif6cD/eLqb/n9lUglpyrUGJ8VYS7qOSjze3kodxVj0Y2M5o3hen8TAEEJSK3SAOro/9WCI6WgoltTrxYUkIUVMxbnZOi3EieSzcbm8
    admin-user: AgBfTJyKvg7B+wNQTBOQwek+wHeTxSyj+R9zWo0EzavLszCAX/qbokmHXkKz5HwdcMeC+2ec8jiX/rGxigESXHe/Mx2iBzy8odLqRayQASzxyuWjycGzTsi8Ts9tqlOk1uDb//Ya3PNFMxuLACOO5NSPI/GfCQ3EvDD/n+CQfxgMhiSFcFZaUEMsoxW8OSyNyyNwMUcLFGTC8Hc/cD3Z3qIles0yskquf5ywgkHJcdtkK/LZnSUw00rxuk1QZgzwgF5KW6t3na6WRbhC7UHRs5T6JvppmlNoixdyLEzjsIxD2tkW7Pl3BjvjMGFMhZ+26cojQFBvhunO6DzdOmGdWXt+nY0mgZJbzte5qp9EcsC6rOVebcRVSAz5DcCXtxwrOO+FJOAITDAICSJnzwAsBNIPt0zIRIWxNn/x607NbQsyGrVFx/ls/+x87UwunzXGyBZZlzjnDEaH7OOToLwoOCj8/fcawh41Pk5ASiBtsKQ7TZhfC8CMq67ZHSkZVdk8GoEjldSlG0TOmzOvV4UtHLzcaDmQJD0KL0+amMl0lV1JOIZgmE6T6pIsAPnN09uHvTGWBu7YylDPloRfOOD+liQdqywJGVaRg4L3ObP1ViGnn8oLTNgrd08p6Akup58SSz+BB9Y79X0ndvmGQQZ6Jja1FFdtvrc4aswQOi/KmvqhIQjkSL/lcIZ3sYlTQnZT6bryvZbUIw==
  template:
    metadata:
      creationTimestamp: null
      name: kc-general
      namespace: auth

