# This is a basic workflow to help you get started with Actions

name: ci-helm-ghcr
permissions:
  packages: write
  contents: read
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # Chart versions
  KEYCLOAK_CNAME: "keycloak"
  KEYCLOAK_CVER: 13.0.0
  POSTGRESQL_CNAME: "postgresql"
  POSTGRESQL_CVER: 12.1.8
  PGADMIN_CNAME: "pgadmin4"
  PGADMIN_CVER: 1.13.6

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "package-charts"
  package-charts:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: print tree
        run: |
          tree
      
      - name: helm lint
        run: |
          helm lint helm/auth/keycloak --strict --values helm/auth/keycloak/values.yaml
          helm lint helm/app/postgresql --strict --values helm/app/postgresql/values.yaml
          helm lint helm/monitoring/pgadmin4 --strict --values helm/monitoring/pgadmin4/values.yaml
          
      - name: helm package
        run: |
          helm package helm/auth/keycloak --version $KEYCLOAK_CVER
          helm package helm/app/postgresql --version $POSTGRESQL_CVER
          helm package helm/monitoring/pgadmin4 --version $PGADMIN_CVER
          
      - name: helm login
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io -u $ --password-stdin
          
      - name: helm push
        if: ${{ github.event_name == 'push' }}
        run: |
          ls
          REPO_OWNER=`echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]'`
          helm push ${KEYCLOAK_CNAME}-${KEYCLOAK_CVER}.tgz oci://ghcr.io/${REPO_OWNER}/charts
          helm push ${POSTGRESQL_CNAME}-${POSTGRESQL_CVER}.tgz oci://ghcr.io/${REPO_OWNER}/charts
          helm push ${PGADMIN_CNAME}-${PGADMIN_CVER}.tgz oci://ghcr.io/${REPO_OWNER}/charts
